/**
 * @license MIT
 * LangJS Server-Side Runtime & Universal HTML Transformer
 * Framework-agnostic runtime that intercepts rendered HTML output from ANY server
 * framework (React SSR, Vue/Nuxt, SvelteKit, Angular, Django, Laravel, Rails, Astro, Express),
 * translates visible text using the persisted lang/lang.json manifest,
 * and allows developers/AI agents to persist corrections to avoid Google inaccuracies.
 */

import fs from 'fs';
import path from 'path';
import { LangJsonManifest, SideBySideRecord } from './scanner';

export interface ServerRuntimeOptions {
  manifestPath?: string;
  initialManifest?: LangJsonManifest;
  defaultLanguage?: string;
  supportedLanguages?: string[];
  autoPersistMissing?: boolean;
  onMissingTranslation?: (text: string, targetLang: string) => Promise<string | null>;
}

export class ServerTranslateRuntime {
  private manifest: LangJsonManifest | null = null;
  private manifestPath: string | null = null;
  private defaultLanguage: string;
  private supportedLanguages: Set<string>;
  private autoPersistMissing: boolean;
  private rtlLanguages = new Set(['ar', 'he', 'iw', 'fa', 'ur', 'yi', 'ps', 'sd', 'ug', 'ku']);

  constructor(options: ServerRuntimeOptions = {}) {
    this.defaultLanguage = options.defaultLanguage || 'en';
    this.supportedLanguages = new Set(options.supportedLanguages || ['en', 'am', 'es', 'fr', 'ja', 'de', 'ar']);
    this.autoPersistMissing = options.autoPersistMissing ?? false;

    if (options.initialManifest) {
      this.manifest = options.initialManifest;
    } else if (options.manifestPath) {
      this.loadManifest(options.manifestPath);
    }
  }

  /**
   * Loads or reloads the lang/lang.json manifest from disk
   */
  public loadManifest(filePath: string): boolean {
    try {
      const resolved = path.resolve(filePath);
      if (fs.existsSync(resolved)) {
        const raw = fs.readFileSync(resolved, 'utf-8');
        this.manifest = JSON.parse(raw);
        this.manifestPath = resolved;
        if (this.manifest?.meta?.targetLanguages) {
          this.manifest.meta.targetLanguages.forEach((l) => this.supportedLanguages.add(l));
        }
        return true;
      }
    } catch (e) {
      console.warn('[LangJS Server] Could not load manifest:', e);
    }
    return false;
  }

  public getManifest(): LangJsonManifest | null {
    return this.manifest;
  }

  public setManifest(manifest: LangJsonManifest) {
    this.manifest = manifest;
  }

  /**
   * Core Universal HTML Transformer
   * Works on raw HTML strings generated by ANY template engine or framework
   */
  public translateHtml(rawHtml: string, targetLang: string): string {
    if (!rawHtml || targetLang === this.defaultLanguage) {
      return rawHtml;
    }

    const dict = this.manifest?.locales?.[targetLang] || {};
    const isRtl = this.rtlLanguages.has(targetLang);

    // 1. Update <html lang="..." dir="..."> tag
    let output = rawHtml.replace(/<html(\s+[^>]*)?>/i, (match, attrs = '') => {
      let cleaned = attrs
        .replace(/\s+lang=["'][^"']*["']/gi, '')
        .replace(/\s+dir=["'][^"']*["']/gi, '');
      return `<html${cleaned} lang="${targetLang}" dir="${isRtl ? 'rtl' : 'ltr'}">`;
    });

    // 2. Protect <script>, <style>, <svg>, <pre>, <code> blocks to prevent parsing code
    const protectedBlocks: string[] = [];
    output = output.replace(/<(script|style|svg|pre|code)([\s\S]*?)<\/\1>/gi, (match) => {
      const placeholder = `___LANGJS_PROTECTED_${protectedBlocks.length}___`;
      protectedBlocks.push(match);
      return placeholder;
    });

    // 3. Replace translatable tag text: >Text<
    output = output.replace(/>([^<>{}\n]+)</g, (match, textContent) => {
      const trimmed = textContent.trim();
      if (!trimmed || trimmed.length < 2) return match;

      // Look up in persisted lang/lang.json dictionary
      const translated = dict[trimmed];
      if (translated && translated !== trimmed) {
        // Preserve surrounding leading/trailing whitespace
        const leading = textContent.match(/^\s*/)?.[0] || '';
        const trailing = textContent.match(/\s*$/)?.[0] || '';
        return `>${leading}${translated}${trailing}<`;
      }
      return match;
    });

    // 4. Replace translatable attributes: placeholder, title, alt, aria-label
    output = output.replace(
      /\b(placeholder|title|alt|aria-label)\s*=\s*(["'])(.*?)\2/gi,
      (match, attrName, quote, attrValue) => {
        const trimmed = attrValue.trim();
        if (!trimmed) return match;

        const translated = dict[trimmed];
        if (translated && translated !== trimmed) {
          return `${attrName}=${quote}${translated}${quote}`;
        }
        return match;
      }
    );

    // 5. Restore protected blocks
    for (let i = 0; i < protectedBlocks.length; i++) {
      output = output.replace(`___LANGJS_PROTECTED_${i}___`, protectedBlocks[i]);
    }

    return output;
  }

  /**
   * Persists an edited or AI-verified translation to lang/lang.json
   * Directly fixes Google inaccuracies in the persisted JSON file
   */
  public persistCorrection(
    sourceText: string,
    targetLang: string,
    correctedTranslation: string,
    editedBy: string = 'developer'
  ): boolean {
    if (!this.manifest) return false;

    // 1. Update locales dictionary
    if (!this.manifest.locales[targetLang]) {
      this.manifest.locales[targetLang] = {};
    }
    this.manifest.locales[targetLang][sourceText] = correctedTranslation;

    // 2. Update sideBySide records
    let foundRecord = this.manifest.sideBySide.find((r) => r.source === sourceText);
    if (!foundRecord) {
      foundRecord = {
        id: `str_${Date.now()}`,
        source: sourceText,
        type: 'tag_text',
        occurrences: [],
        translations: {
          [this.defaultLanguage]: sourceText,
          [targetLang]: correctedTranslation,
        },
        verified: true,
        lastEditedBy: editedBy,
        notes: `Correction saved by ${editedBy}`,
      };
      this.manifest.sideBySide.push(foundRecord);
    } else {
      foundRecord.translations[targetLang] = correctedTranslation;
      foundRecord.verified = true;
      foundRecord.lastEditedBy = editedBy;
      foundRecord.notes = `Verified and updated by ${editedBy} to fix machine translation error.`;
    }

    // 3. Write to disk if path is known
    if (this.manifestPath) {
      try {
        fs.writeFileSync(this.manifestPath, JSON.stringify(this.manifest, null, 2), 'utf-8');
        return true;
      } catch (e) {
        console.error('[LangJS Server] Error persisting correction to disk:', e);
      }
    }
    return true;
  }

  /**
   * Express / Connect middleware generator
   */
  public createMiddleware() {
    return (req: any, res: any, next: () => void) => {
      // Detect language from query ?lang=..., cookie, or Accept-Language header
      const requestedLang =
        req.query?.lang ||
        req.cookies?.langjs_language ||
        req.headers?.['accept-language']?.split(',')[0]?.split('-')[0] ||
        this.defaultLanguage;

      if (!this.supportedLanguages.has(requestedLang) || requestedLang === this.defaultLanguage) {
        return next();
      }

      // Intercept res.send
      const originalSend = res.send;
      res.send = (body: any) => {
        if (typeof body === 'string' && res.getHeader('content-type')?.toString().includes('text/html')) {
          const transformed = this.translateHtml(body, requestedLang);
          return originalSend.call(res, transformed);
        }
        return originalSend.call(res, body);
      };

      next();
    };
  }
}
